### ISSUE TITLE
Nodeprompt cause text to render incorrectly when typing long commands

### ISSUE THREAD

**Issue by Reinmar** [oleq/nodeprompt#11]
![may-17-2017 16-59-31](https://cloud.githubusercontent.com/assets/156149/26160773/6e95a344-3b22-11e7-9859-be6971b4e524.gif)

**Comment by Reinmar** [comment]
Downgrading to 0.0.3 helped for me, so 0.0.4 is the first affected version.

**Comment by oleq** [comment]
I just released [v1.0](https://github.com/oleq/nodeprompt/releases/tag/1.0.0). Can you confirm this is still an issue?

**Comment by oleq** [comment]
Closed in a4c738e603.
